name: Docker Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Expose git commit data
      uses: rlespinasse/git-commit-data-action@v1
    
    - name: Build the Docker image
      run: docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/petclinic:${{ env.GIT_COMMIT_SHORT_SHA }}" .

    - name: Trivy Scan Image
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: "${{ secrets.DOCKERHUB_USERNAME }}/petclinic:${{ env.GIT_COMMIT_SHORT_SHA }}"
        format: 'table'
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Docker Login
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/petclinic:${{ env.GIT_COMMIT_SHORT_SHA }} 

    

